#import "./RenderableScene.gql"

query editDevice($id: ID!) {
  device(id: $id) {
    id
    name
    ledCount
    ledStrip
    scene {
      ...RenderableScene
    }
  }
  scenes {
    ...RenderableScene
  }
}