mutation NewDevice ($device: DeviceInput!) {
  createDevice(fields: $device) {
    result {
      id
      name
      ledCount
      gpioPin
      ledStrip
      scene {
        id
      }
    }
  }
}